name: fancy_menu
description: A simple animated  menu list for Flutter, Adjustable radius, colors, text size, Icons and background color.
version: 0.0.1
author: Abin Mathew [email : abinmathew456@gmail.com]
homepage: https://github.com/abinmathew456456/fancy_menu.git

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


